apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1601
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1601
  template:
    metadata:
      labels:
        app: demo1601
    spec:
      containers:
      - name: demo1601
        image: ghcr.io/dsanchor/demo-copilot-1601/demo1601:#IMAGE_TAG#
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo1601
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: demo1601